Обработка исключений
====================

* `Исключения и их обработка`: [Исключения и их обработка](http://kostin.ws/java/java-exceptions.html)
* `Глава 10 Обработка исключений`: [Глава 10 Обработка исключений](http://www.softzenware.com/java/10.htm)
* `Исключения в Java, Часть I (try-catch-finally)`: [Исключения в Java, Часть I (try-catch-finally)](http://habrahabr.ru/company/golovachcourses/blog/223821/)
* `Исключения в Java, Часть II (checked/unchecked)`: [Исключения в Java, Часть II (checked/unchecked)](http://habrahabr.ru/company/golovachcourses/blog/225585/)
* `Java / Типы исключений в Java`: [Java / Типы исключений в Java](http://www.quizful.net/interview/java/exception-types)
* `http://aectann.wikidot.com/java-exceptions-handling`: [http://aectann.wikidot.com/java-exceptions-handling](http://aectann.wikidot.com/java-exceptions-handling)


###Описание

> Исключение происходит когда прграмма неможет продолжать выполнение ТОГДА в этом случае Java-машина создаем объект-исключения И переключается на него ЧТОБЫ пользователь мог корректно завершить работу с этой програмой.

> Относительно области применения исключения бывают: "аппаратные", "внешние", "программные":

1. `Error`: исключительные ситуации (серъезные ошибки) которые связаны при работе JAVA-машины на аппаратном уровне (железом) - их нет смысла вообще никак обрабатывать, потому-что они в принципе неподдерживаются этой JAVA-машиной

3. `RuntimeException`: исключительные ситуации (неконтролируемые ошибки) которые связаны с передачей внешних данных ИХ наличие невозможно предугадать на конкретный момент времени - их необизательно обрабатывать как исключения (нужно использовать проверку валидности по условию)...

2. `Exception`: исключительные ситуации (контролируемые ошибки) которые связаны при работе внутри программы ИХ наличие можно и нужно предугадывать - их нужно обрабатывать как исключения!


> Все объекты-исключения имеют общего предка - "Trowable".

> Иерархическую структуру для объектов-исключения можно разделить на 3-группы: "Error" (аппаратные), "RuntimeException" (внешние, которые тоже наследуются от Exception), "Exception" (программные)

> Также все исключения можно разделить на 2-группы:

>> "CHECKED" (контролируемые исключения) - сюда относятся только "Exception" (программные) исключения

>> "UNCHECKED" (неконтролируемые исключения) - сюда относятся "Error" (аппаратные) и "RuntimeException" (внешние) исключения



> Существует особая разница для понимания: ВОЗБУДИТЬ ИСКЛЮЧЕНИЕ и БРОСИТЬ ИСКЛЮЧЕНИЕ.
>> "исключительная ситуация" - это непредвиденный случай при выполнении чего-то (когда программа ведет себя ненормально и JAVA-машина незнет как с этим работать)... - такое поведение программы приводит к "возбуждению исключения".
"возбужденные исключения" они обрабатываются по умолчанию виртуальной JAVA-машинной, тобишь, объекты-исключения автоматичнски создаются испольняющей средой JAVA - после этого JAVA-машина прекращает (нормальную) работу программы и переклячается на объекты-исключения, которые позволяют корректно завершить для пользователя работу с этой программой

>> Если нужно какую-то конкретную ошибку допонительно обработать (например: проверка на NULL|0, проверка на отрицательное значение, ...) - в этом случае можно "бросить исключение", чтобы потом его обработать в блоке "catch"...

>> Блок "catch" обычно служит для того чтобы ловить какие-нибудь "RuntimeException" (UNCHECKED) исключения для дополнительной обработки.

>> Блок "try" может иметь несколько/много блоков "catch" чтобы ловить разные типы ошибок И эти типы-исключений для ошибок должны быть выстроены в порядке с-низу в-верх (сперва обрабатывается самый нижный-класс по иерархии, а в конце самый верхний).

>> Самым последним нужно ставить блок "finally" - это гарантия на случай если ниодин из блоков "catch" небудет задействован/найден.

>> И поскольку Блок "try" позволяет иметь много блоков "catch". Также и метод может иметь много разных типов исключений которые он бросает

>> Бросить исключение можно несколькими способами:
>>> Можно перехватывать брошенное исключение (на случай если такие будут) в блоке "try", чтобы потом в блоке "catch" его отловить и обработать - но это только на тот случай если такие будут

>>> А можно принудительно/гарантированно бросить объект-исключения с помощью "throw" (исключение-throw можно бросить либо в блоке "try/catch" либо пометить метод как "throws" что он может возбуждать исключения типа объекта-исключения) - при этом (нормальное) выполнение программы тут-же прервется


###Резюме

>> Тобишь, блок try/catch/finally служит чтобы перехватывать исключения для дополнительной обработки.

>> если будет (возбуждена или брошена) исключительная ситуация JAVA-машина сама в любом случае будет ловить и обработать (по умолчанию) его, даже без try/catch...

>> после того как принудительно будет брошено исключение "throw" - после этого (нормальное) выполение программы прервется и JAVA-машина переключиться на объект-исключения

>> объекты-исключения (которые способны их возбуждать/перехватывать/ловить) могут использоваться библиотечные или могут быть созданы...


К `Error` (UNCHECKED) можно отнести: OutOfMemoryError, VirtualMachineError, StackOverflowError, NoSuchMethodError

К `RuntimeException` (UNCHECKED) можно отнести: NullPointetrException, IndexOutOfBoundsException, ArrayIndexOutOfBoundsException, ArichmeticException, IllegalArgumentException

К `Exception` (CHECKED) можно отнести: IOException, EOFException, ObjectStreamException, InterrupteException